const MEMBERS = [
  {
    id: 1,
    year: 4,
    nickname: '니니',
    name: '김유빈',
    part: 'IOS',
    position: '회장',
    github: null,
    sex: 'w',
    project: null
  },
  {
    id: 2,
    year: 4,
    nickname: '케빈',
    name: '김근식',
    part: 'SPRING',
    position: '부회장',
    github: '600gramSik',
    sex: 'm',
    project: null
  },
  {
    id: 3,
    year: 4,
    nickname: '해누',
    name: '김현우',
    part: 'SPRING',
    position: '부회장',
    github: 'khw18',
    sex: 'm',
    project: null
  },
  {
    id: 4,
    year: 4,
    nickname: '원스',
    name: '김유정',
    part: 'ANDROID',
    position: '파트장',
    github: null,
    sex: 'm',
    project: null
  },
  {
    id: 5,
    year: 4,
    nickname: '폴',
    name: '김필규',
    part: 'IOS',
    position: '파트장',
    github: 'pingu00',
    sex: 'm',
    project: null
  },
  {
    id: 6,
    year: 4,
    nickname: '포디',
    name: '정서현',
    part: 'WEB',
    position: '파트장',
    github: 'JSH99',
    sex: 'w',
    project: null
  },
  {
    id: 7,
    year: 4,
    nickname: '동키',
    name: '김동현',
    part: 'SPRING',
    position: '파트장',
    github: 'Ddonghyeop',
    sex: 'm',
    project: null
  },
  {
    id: 8,
    year: 4,
    nickname: '민팍',
    name: '박민희',
    part: 'NODE',
    position: '파트장',
    github: 'himinsunsine',
    sex: 'w',
    project: null
  },
  {
    id: 9,
    year: 4,
    nickname: '검정',
    name: '권혁찬',
    part: 'ANDROID',
    position: '챌린저',
    github: null,
    sex: 'm',
    project: null
  },
  {
    id: 10,
    year: 4,
    nickname: '코코',
    name: '최진규',
    part: 'ANDROID',
    position: '챌린저',
    github: null,
    sex: 'm',
    project: null
  },
  {
    id: 11,
    year: 4,
    nickname: '콘',
    name: '이현호',
    part: 'IOS',
    position: '챌린저',
    github: null,
    sex: 'm',
    project: null
  },
  {
    id: 12,
    year: 4,
    nickname: '딩동',
    name: '이동현',
    part: 'IOS',
    position: '챌린저',
    github: 'taipaise',
    sex: 'm',
    project: null
  },
  {
    id: 13,
    year: 4,
    nickname: '스히',
    name: '백서희',
    part: 'IOS',
    position: '챌린저',
    github: 'soycong',
    sex: 'w',
    project: null
  },
  {
    id: 14,
    year: 4,
    nickname: '위즈덤',
    name: '정슬기',
    part: 'IOS',
    position: '챌린저',
    github: null,
    sex: 'w',
    project: null
  },
  {
    id: 15,
    year: 4,
    nickname: '린니',
    name: '이혜린',
    part: 'WEB',
    position: '챌린저',
    github: 'HYERINI',
    sex: 'w',
    project: null
  },
  {
    id: 16,
    year: 4,
    nickname: '아마다',
    name: '조재석',
    part: 'WEB',
    position: '챌린저',
    github: 'PRISED(찾아복)',
    sex: 'm',
    project: null
  },
  {
    id: 17,
    year: 4,
    nickname: '주니',
    name: '김영준',
    part: 'IOS',
    position: '챌린저',
    github: null,
    sex: 'm',
    project: null
  },
  {
    id: 18,
    year: 4,
    nickname: '피딕',
    name: '황인성',
    part: 'IOS',
    position: '챌린저',
    github: null,
    sex: 'm',
    project: null
  },
  {
    id: 19,
    year: 4,
    nickname: '제이',
    name: '김영재',
    part: 'WEB',
    position: '챌린저',
    github: null,
    sex: 'm',
    project: null
  },
  {
    id: 20,
    year: 4,
    nickname: '데이빗',
    name: '김태영',
    part: 'WEB',
    position: '챌린저',
    github: 'kimtaeyoung201910794',
    sex: 'm',
    project: null
  },
  {
    id: 21,
    year: 4,
    nickname: '우비',
    name: '박원우',
    part: 'WEB',
    position: '챌린저',
    github: null,
    sex: 'm',
    project: null
  },
  {
    id: 22,
    year: 4,
    nickname: '매튜',
    name: '김용민',
    part: 'WEB',
    position: '챌린저',
    github: 'dydals3440',
    sex: 'm',
    project: null
  },
  {
    id: 23,
    year: 4,
    nickname: '지구',
    name: '안지수',
    part: 'WEB',
    position: '챌린저',
    github: null,
    sex: 'w',
    project: null
  },
  {
    id: 24,
    year: 4,
    nickname: '제이미',
    name: '김준환',
    part: 'SPRING',
    position: '챌린저',
    github: 'catturtle123',
    sex: 'm',
    project: null
  },
  {
    id: 25,
    year: 4,
    nickname: '디채',
    name: '김채연',
    part: 'SPRING',
    position: '챌린저',
    github: 'yeon-22k',
    sex: 'w',
    project: null
  },
  {
    id: 26,
    year: 4,
    nickname: '제이스',
    name: '임재영',
    part: 'SPRING',
    position: '챌린저',
    github: 'limjustin',
    sex: 'm',
    project: null
  },
  {
    id: 27,
    year: 4,
    nickname: '사하',
    name: '윤근수',
    part: 'SPRING',
    position: '챌린저',
    github: 'rlJzr',
    sex: 'm',
    project: null
  },
  {
    id: 28,
    year: 4,
    nickname: '링키',
    name: '윤수빈',
    part: 'SPRING',
    position: '챌린저',
    github: 'soogoori',
    sex: 'w',
    project: null
  },
  {
    id: 29,
    year: 4,
    nickname: '하비',
    name: '이승주',
    part: 'SPRING',
    position: '챌린저',
    github: 'WinsomeJoo',
    sex: 'm',
    project: null
  },
  {
    id: 30,
    year: 4,
    nickname: '블루',
    name: '최민주',
    part: 'SPRING',
    position: '챌린저',
    github: null,
    sex: 'm',
    project: null
  },
  {
    id: 31,
    year: 4,
    nickname: '윤',
    name: '권오윤',
    part: 'SPRING',
    position: '챌린저',
    github: 'k-oyun',
    sex: 'm',
    project: null
  },
  {
    id: 32,
    year: 4,
    nickname: '세헌',
    name: '호세헌',
    part: 'SPRING',
    position: '챌린저',
    github: 'seheonnn',
    sex: 'm',
    project: null
  },
  {
    id: 33,
    year: 4,
    nickname: '한뉴',
    name: '한유성',
    part: 'SPRING',
    position: '챌린저',
    github: null,
    sex: 'm',
    project: null
  },
  {
    id: 34,
    year: 4,
    nickname: '우현',
    name: '이현우',
    part: 'SPRING',
    position: '챌린저',
    github: 'HyunwooYi',
    sex: 'm',
    project: null
  },
  {
    id: 35,
    year: 4,
    nickname: '이네',
    name: '설인혜',
    part: 'SPRING',
    position: '챌린저',
    github: null,
    sex: 'w',
    project: null
  },
  {
    id: 36,
    year: 4,
    nickname: '찬',
    name: '안성찬',
    part: 'NODE',
    position: '챌린저',
    github: null,
    sex: 'm',
    project: null
  },
  {
    id: 37,
    year: 4,
    nickname: '쫑',
    name: '김종한',
    part: 'NODE',
    position: '챌린저',
    github: 'entere77',
    sex: 'm',
    project: null
  },
  {
    id: 38,
    year: 4,
    nickname: '뻔뻔',
    name: '김건',
    part: 'NODE',
    position: '챌린저',
    github: 'funfungun',
    sex: 'm',
    project: null
  },
  {
    id: 39,
    year: 4,
    nickname: '예닝',
    name: '문예윤',
    part: 'NODE',
    position: '챌린저',
    github: null,
    sex: 'w',
    project: null
  },
  {
    id: 40,
    year: 4,
    nickname: '하나빈',
    name: '이원빈',
    part: 'NODE',
    position: '챌린저',
    github: null,
    sex: 'm',
    project: null
  },
  {
    id: 41,
    year: 4,
    nickname: '엘레나',
    name: '권유정',
    part: 'DESIGN',
    position: '챌린저',
    github: null,
    sex: 'w',
    project: null
  },
  {
    id: 42,
    year: 4,
    nickname: '디아',
    name: '전지민',
    part: 'DESIGN',
    position: '챌린저',
    github: null,
    sex: 'w',
    project: null
  },
  {
    id: 43,
    year: 4,
    nickname: '깐',
    name: '김가은',
    part: 'DESIGN',
    position: '챌린저',
    github: null,
    sex: 'w',
    project: null
  },
  {
    id: 44,
    year: 4,
    nickname: '덕구',
    name: '이다슬',
    part: 'PLAN',
    position: '챌린저',
    github: null,
    sex: 'w',
    project: null
  },
  {
    id: 45,
    year: 4,
    nickname: '와제',
    name: '정여진',
    part: 'PLAN',
    position: '챌린저',
    github: null,
    sex: 'w',
    project: null
  }
];

export { MEMBERS };
